### ISSUE TITLE
new item Orboreal Distinguishment (error)

### ISSUE THREAD

**Issue by MubarakHAlketbi** [t-mart/ItemVersion#10]
**ItemVersion Version**
ItemVersion v2021.10.0

**Description**
ERROR - ItemVersion v2021.10.0 - Could not find game version for item with id 185834. You may be running an old version of ItemVersion or this item may not be in our database. Please upgrade to the latest version from CurseForge and/or create an issue on the GitHub project page. 

**Reproduction Steps**
item is newly added in patch 9.0.5 [Orboreal Distinguishment](https://www.wowhead.com/item=185834/orboreal-distinguishment)

**Expected Behvaior**
no error should be made as it is a new item just add it to the addon

**Comment by t-mart** [comment]
Thanks for the report!

I think the last week's automatic data refresh of the item database didn't
pick up the new patch.

I'm not free tonight, but will try to work on this tomorrow. At the very
least, it should be good next Tuesday with the next refresh.

**Comment by t-mart** [comment]
@MHketbi, a new release has been made available on CurseForge.

Do you still see issues with the new 9.0.5 items after upgrading?
