### ISSUE TITLE
Error - Missing Item (Flask of Vrykul Blood - 34024)

### ISSUE THREAD

**Issue by HubNuht** [t-mart/ItemVersion#13]
**ItemVersion Version**
2021.21.0

**Description**
Could not find game version for item with id 34024

**Reproduction Steps**

1. Mouse over [Flask of Vrykul Blood](https://wowhead.com/item=34024)

**Expected Behavior**
No error printed in Chat window, and ItemVersion information appear in tooltip

**Comment by t-mart** [comment]
Thanks for the report, @kohkuhnuht!

Wowhead states that "this item is not available to players", which is a prerequisite for inclusion in ItemVersion's database.

How did you obtain this item (or get its tooltip to show)? If there's a common way that other players might encounter it, I could add it manually.

**Comment by HubNuht** [comment]
Thank you for your time, @t-mart 

You are correct, Wowhead states that it is not available to players.

I obtained it from [Apply Heat and Stir](https://www.wowhead.com/quest=11306/apply-heat-and-stir) quest while levelling as a Horde through Howling Fjord in Northrend.

**Comment by t-mart** [comment]
Closing. Database doesn't get these kinds of items.
