### ISSUE TITLE
Error - Missing Item (Reins of the Swift Spectral Tiger - 33225)

### ISSUE THREAD

**Issue by antonioesposito** [t-mart/ItemVersion#14]
**ItemVersion Version**
2021.32.0

**Description**
Could not find game version for item with id 33225

**Reproduction Steps**

1. Mouse over [Reins of the Swift Spectral Tiger](https://www.wowhead.com/item=33225/reins-of-the-swift-spectral-tiger)

**Expected Behvaior**
Error printed in Chat window, and ItemVersion information doesn't appear in tooltip

**Screenshots/Videos/GIFs/etc**
[Link to the screen](https://media-upload.net/uploads/Wg3qUlvukAce.jpg)

**Comment by t-mart** [comment]
Thanks for the bug report.

This is one of many reports for items that are "not available to players". Can't do anything about these. We don't have the data for it.
