### ISSUE TITLE
Rippling Fur

### ISSUE THREAD

**Issue by Ophilla** [t-mart/ItemVersion#15]
**ItemVersion Version**
 ItemVersion v2021.34.0

**Description**
Item tooltip does not display any item version and this error is printed to the chat:

ERROR - ItemVersion v2021.34.0 - Could not find game version for item with id 44760. You may be running an old version of ItemVersion or this item may not be in our database. Please upgrade to the latest version from CurseForge and/or create an issue on the GitHub project page.

**Reproduction Steps**
1. Mouse over [Rippling Fur](https://www.wowhead.com/item=44760/rippling-fur)

**Expected Behvaior**
No error, proper version displayed in the tooltip

**Comment by t-mart** [comment]
As you may have seen on wowhead, "This item is not available to players." This addon isn't capable of knowing about items like that.

This is the same issue as #13 and #14.

I think what I may just do in this case is blacklist the item(s). You wouldn't be get the tooltip, but you also wouldn't get the error.

Also, just curious, how are you encountering this item? Is it in your inventory?
