### ISSUE TITLE
RU localization and change .toc file

### ISSUE THREAD

**Issue by Hollicsh** [t-mart/ItemVersion#16]
Hello !
Is it possible to add Russian localization ?
Also you forgot to change  **## Interface: 90005**  ->  **## Interface: 90105**

**Comment by t-mart** [comment]
Interface has been updated in latest version. Thanks!

Localization is something I've considered, but I don't really know how to do it. Keeping this open as a to-do item. If anyone can help with this, please let me know.

I'd imagine we'd need at least two things:
- A mechanism to change the in game text to the player's locale
- Translators

**Comment by t-mart** [comment]
Worked on localization in #22. Fortunately, the language that this addon uses is, more or less, present in [GlobalStrings.lua](https://www.townlong-yak.com/framexml/beta/GlobalStrings.lua) (and, for example, compare that with its [Russian counterpart](https://www.townlong-yak.com/framexml/live/GlobalStrings.lua/RU)). Blizzard maintains translations of all strings in that file to power its official UI in the game for every supported locale. Therefore, no explicit translation work was needed by us -- we're just reusing strings from there that happen to fit our needs.

Let me know if you encounter any text that's not translated.
