### ISSUE TITLE
Error: Item not found (Bottle of Wildfire)

### ISSUE THREAD

**Issue by DockieB** [t-mart/ItemVersion#18]
I received this error in Ashenvale for the quest [Of Their Own Design], quest ID 13595. 

ERROR - ItemVersion v2022.17.0 - Could not find game version for item with id 44967. You may be running an old version of ItemVersion or this item may not be in our database. Please upgrade to the latest version from CurseForge and/or create an issue on the GitHub project page.

My add-on says it's up to date in CurseForge.

**Comment by t-mart** [comment]
Sorry for the late reply.

Are you talking about [Bottle of Wildfire](https://www.wowhead.com/item=44967/bottle-of-wildfire)?

As of now, that item is "not available to players". The ItemVersion database doesn't store items like that.
