### ISSUE TITLE
Itemversion  v2022.17.0 missing itemnr: 192450 Coral staff

### ISSUE THREAD

**Issue by Vebepa** [t-mart/ItemVersion#19]
Hi! 

Item nr: 192450 dosn't seem to be in the database atm. every time i mouse over my staff i get this error :

ERROR - ItemVersion v2022.17.0 - Could not find game version for item with id 192450. You may be running an old version of ItemVersion or this item may not be in our database. Please upgrade to the latest version from CurseForge and/or create an issue on the GitHub project page. 

There is no update availble to download atm

**Comment by t-mart** [comment]
This was added in the latest release. Closing.
