### ISSUE TITLE
Provisional patch for Retail 10.0.2

### ISSUE THREAD

**Issue by tflo** [t-mart/ItemVersion#28]
Since the addon is not working with 10.0.2, here a _provisional_ patch for version 2022.42.5:

***

Change line 49 in Tooltip.lua from:

<strike>
<pre lang="lua">GameTooltip:HookScript("OnTooltipSetItem", OnTooltipSetItem)
</pre>
</strike>

to

```lua
TooltipDataProcessor.AddTooltipPostCall(Enum.TooltipDataType.Item, OnTooltipSetItem)
```

To get rid of errors from comparison tooltips (and probably some other), you can optionally add an early return immediately _before_ line 25:

```lua
if not tooltip.GetItem then return end
```

***

I'm not very familiar with the new tooltip API, but this does the trick for me, until the addon gets updated. Only tested on WoW Retail.

– Tom

**Comment by t-mart** [comment]
Hi, Tom.

Thank you for writing in! I will take a look at this over the next few days.

I really appreciate the code suggestions.

**Comment by t-mart** [comment]
Fixed with https://www.curseforge.com/wow/addons/itemversion/files/4100109

**Comment by tflo** [comment]
Thank you!
