### ISSUE TITLE
ItemVersion: Missing entry for 'World of Warcraft'

### ISSUE THREAD

**Issue by Hollicsh** [t-mart/ItemVersion#35]
### What version of ItemVersion are you running?

ItemVersion-2022.47.2

### What is your issue?

**6x AceLocale-3.0-6: ItemVersion: Missing entry for 'World of Warcraft'
[string "@ItemVersion/Tooltip.lua"]:50: in function <ItemVersion/Tooltip.lua:35>
[string "=(tail call)"]: ?
[string "@ItemVersion/Options.lua"]:80: in function `PreviewTooltipText'
[string "@ItemVersion/Options.lua"]:225: in function `GetOptions'
[string "@ItemVersion/Init.lua"]:12: in function <ItemVersion/Init.lua:7>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>**

Immediately after entering the game world, I get this error.
Maybe it has something to do with ElvUI.

**Comment by t-mart** [comment]
Thanks for the report. This error is about a missing translation for a string that yields `World of Warcraft` in English, or whatever the translation is in other languages. 

Which version/flavor of the game are you playing? I haven't seen this yet.

**Comment by Hollicsh** [comment]
> Which version/flavor of the game are you playing? I haven't seen this yet.

Retail 10.0.2.46741

**Comment by t-mart** [comment]
Ah, I think this was fixed.

There was a time when I was calling the first "expansion" _World of Warcraft_. I've since changed that to be _Classic_. And, there's been a lot of development in the past few days, so I might have accidentally included that in the version that you downloaded.

Would you please try a recent build, such as this one?: <https://github.com/t-mart/ItemVersion/actions/runs/3544425832> (See downloadable artifact at the bottom.)

Let me know if you still encounter the issue.

**Comment by t-mart** [comment]
(Also, thanks again for your help on the Russian language translations. If you want to add your name to the [`AUTHORS` file](https://github.com/t-mart/ItemVersion/blob/master/AUTHORS), please make a PR.

**Comment by Hollicsh** [comment]
I will test the new version as soon as I get home.
Thank u !

**Comment by t-mart** [comment]
In that case, try the latest release: https://www.curseforge.com/wow/addons/itemversion/files/4110860

**Comment by t-mart** [comment]
Going to close this for now -- I'm fairly sure its fixed. Feel free to reopen if you encounter it still.

**Comment by Hollicsh** [comment]
Oh sorry ..
Yea, now it's fine !
