### ISSUE TITLE
[suggestion] Add the Command key (Mac) as option to the tooltip modifier keys

### ISSUE THREAD

**Issue by tflo** [t-mart/ItemVersion#36]
### What version of ItemVersion are you running?

2022.47.2

### What is your issue?

Thanks for adding the tooltip modifier keys.

For us Mac users, it would be nice to have the option to set the Command key as modifier for the tooltip, as this is our main modifier and in best thumb position.

For details how to do this (it is really easy), please see my post for [ATT](https://github.com/DFortun81/AllTheThings/issues/1131), which is a very similar case. (Or [Leatrix](https://github.com/leatrix/leatrix-plus/issues/88).).

This is for WoW Retail. I currently don't play Classic, so I don't know if it will work there. (I have one WotLK Classic toon though, so I could test it.)

Thanks in advance for considering,

– Tom

### Can you provide any screenshots of what you describe?

n/a

**Comment by tflo** [comment]
Just noticed that your addon is fully built on Ace libraries, including config. So it seems you are the wrong addressee in this case. (Somewhat surprised that they still have not added the modifier.)

PS: Posted in the [Ace Issues](https://www.curseforge.com/wow/addons/ace3/issues/618) now.

**Comment by t-mart** [comment]
I do think this is possible without a fix from Ace. I'm not using any of their API to do the modifier detection or configuration.

I didn't know there was a meta modifier function until I read your linked post: `IsMetaKeyDown()`. I think I can incorporate that right into this area: <https://github.com/t-mart/ItemVersion/blob/e243f08388268e5a83ee12846d2da2c9a267e7bc/ItemVersion/Tooltip.lua#L22>

Configuration takes place here: <https://github.com/t-mart/ItemVersion/blob/e243f08388268e5a83ee12846d2da2c9a267e7bc/ItemVersion/Options.lua#L202-L214>

I'll start working on this soon. Because I'm on Windows, would you be willing to give me feedback on how it works for Mac users after I commit it?

**Comment by tflo** [comment]
Well, if you can add the modifier without hooking into the Ace stuff, that would be great of course. (When I saw the AceConfig lib and that the modifier is completely missing there, I gave up ;)

> would you be willing to give me feedback on how it works for Mac 

Sure. This is not the first addon where I annoy the author with that suggestion. Dominos, Clicked, LeatrixPlus, ATT were before you ;)

**Comment by tflo** [comment]
I'm not sure if you saw it in the linked instructions in the OP: You can test for the Mac platform with `IsMacClient()`. That means you can conveniently hide the option for platforms that have only 3 modifier keys.

**Comment by t-mart** [comment]
I added a test build to #38. Please check it out and let me know if it works as expected, @tflo.

**Comment by tflo** [comment]
Damn, you did it! It works perfectly! (Even combos work)

Just a minor cosmetic thing for the GUI: The short name of the key is "Cmd", so it would be "CMD" in all uppercase.

"META" is only used by Blizz in the API, on the Mac nobody knows the key under that name. Blizz also uses "CMD" in the Keybinding settings, for example:

<details>
<summary>Screenshot</summary>


<img width="611" alt="WoWScrnShot_112422_225528" src="https://user-images.githubusercontent.com/1410282/203868337-27ef6e3a-a285-4d29-b787-d0c83f8f6a35.png">

</details>

***
Btw, also the new options for the color settings are great. Before, I always had difficulties to quickly spot the line in my overloaded tooltips ;)

**Comment by tflo** [comment]
Just tested it briefly in WotLK Classic, it works great there too!

**Comment by t-mart** [comment]
Good stuff.

This has been merged.

If you would like to add your name to the [`AUTHORS` file,](https://github.com/t-mart/ItemVersion/blob/master/AUTHORS) please make a PR.
