### ISSUE TITLE
Missing Korean translation

### ISSUE THREAD

**Issue by t-mart** [t-mart/ItemVersion#51]
### What is your client flavor? (Retail, Wrath, or Classic)

all

### What version of ItemVersion do you have installed?

2022.48.1

### What platform are you playing on? (Windows, Mac, or Linux)

all

### What is the bug? And, what should happen instead?

From <https://www.curseforge.com/wow/addons/itemversion#c14>:

>> 3x AceLocale-3.0-6: ItemVersion: Missing entry for '격아'
[string "@ItemVersion/Tooltip.lua"]:55: in function <ItemVersion/Tooltip.lua:42>
[string "=(tail call)"]: ?
[string "@ItemVersion/Options.lua"]:25: in function <ItemVersion/Options.lua:9>
[string "@ItemVersion/Options.lua"]:80: in function <ItemVersion/Options.lua:77>
[string "@ItemVersion/Options.lua"]:37: in function <ItemVersion/Options.lua:35>
[string "=[C]"]: ?
[string "@Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

> hi

>> The above error occurs when using "Use short expansion names"
>>I am requesting a correction.

**Comment by next96** [comment]
I did exactly what you said, but I get the same error.

**Comment by next96** [comment]
`local addonName = ...

local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "koKR")
if not L then return end

L["Tooltip"] = "툴팁"
L["Added in"] = "추가: "
L["Show prefix"] = "접두사 표시"
L["Prefix the tooltip line with a label"] = "확장팩 정보에 접두사 표시"
L["Prefix color"] = "접두사 색상"
L["Prefix"] = "접두사"
L["The color of the prefix"] = "접두사 색상 설정"
L["Use short expansion names"] = "확장팩 이름을 짧게 표시"
L["Abbreviate the item's expansion"] = "확장팩 이름을 단축어로 표시합니다."
L["Expansion color"] = "확장팩 색상"
L["The color of the expansion"] = "확장팩 색상 설정"
L["Show version"] = "버전 표시"
L["Show the version in which the item was added"] = "아이템이 추가된 버전을 표시합니다."
L["Version color"] = "버전 색상"
L["The color of the version"] = "버전 색상 설정"
L["TBC"] = "불성"
L["WotLK"] = "리분"
L["Cata"] = "대격변"
L["MoP"] = "판다"
L["WoD"] = "드군"
L["BfA"] = "격아"
L["SL"] = "어둠땅"
L["DF"] = "용군단"
L["Show for unknown items"] = "미확인 아이템 표시"
L["Show the tooltip line even when the item is not in the database"] = "DB에 없는 아이템을 툴팁에 표시합니다."
L["Modifier keys"] = "기능키"
L["Display the tooltip only when the selected modifier keys being are pressed. " ..
    "(No selections means always show.)"] = "툴팁에 정보를 표시할 때 기능키를 눌러야 합니다. (선택하지 않으면 기본적으로 모두 보입니다.)"
L["Include community updates"] = "커뮤니티 업데이트 포함"
L["Including community updates changes some items' version/expansion to the one " ..
            "that players expect. For example, the herb [Marrowroot] was actually added towards " ..
            "the end of BfA in pre-release development, but was only obtainable in SL. With this " ..
            "option turned on, ItemVersion would report SL in this case, instead of BfA.\n\n" ..
            "Because the updates are non-canonical, the version number will be a placeholder one: " ..
            "the major part will be that of the new expansion, but the lesser parts will be zeroed.\n\n" ..
            "If you encounter an item that is not fixed by these updates, please consider " ..
            "reporting it to the project page."] = "커뮤니티 업데이트를 포함하면 일부 아이템의 버전 및 확장팩 정보가 변경됩니다." ..
	    "예를 들어 [골수뿌리]라는 약초 아이템은 격아 말기에 추가되었지만, 실제로는 어둠땅에서만 채집할 수 있습니다." ..
	    "그래서 이 설정을 사용하면 어둠땅에 추가된 아이템으로 표시됩니다." ..
	    "이 업데이트는 비공식이기 때문에 버전표시가 한자리 입니다. 주요 부분은 새로운 확장팩의 버전이지만, 더 작게 되면 0이 됩니다." ..
	    "이러한 업데이트로 변경되지 않는 아이템들이 있다면 프로젝트 페이지에 보고해주세요."

L["usage"] = "사용법"
L["subcommand"] = "명령어"
L["Available Subcommands"] = "명령어를 사용합니다."
L["Opens the configuration window"] = "설정창을 엽니다."
L["Opens a window with information to assist in creating an issue"] = "이슈되는 내용의 도움이 될만한 정보 창을 엽니다."
L["Displays the version of ItemVersion"] = "ItemVersion의 버전을 표시합니다."
L["Shows this help"] = "이 도움말을 표시합니다."
L["%s Issue Information"] = "%s 이슈 정보"
L["Copy and paste this data when making a new issue for ItemVersion."] = "ItemVersion에 대한 새 이슈는 이 데이터를 복사하여 붙여넣기 하세요."

-- these expac strings aren't known in non-mainline, unfortunately
L["Battle for Azeroth"] = "격전의 아제로스"
L["Shadowlands"] = "어둠땅"
L["Dragonflight"] = "용군단"`

**Comment by next96** [comment]
I didn't know how to use it, so I uploaded the contents of the Korean file as it is.

Please let me know if there are any mistakes.

I did the same as you wrote, but I get an error.

**Comment by t-mart** [comment]
Thanks for doing the translation!

I'll take a look at this soon.

**Comment by t-mart** [comment]
Ah, perhaps you forgot to add the reference in `locales.xml`? See how I did this [here](https://github.com/t-mart/ItemVersion/pull/57/commits/d3721dd50ec801fbd51a0f5dd4d2490b8d857384#diff-9ebce9118171ca3a3cac6a5764144709edb378fd5574f48c6df317413f831211). You can test it out with this zip: https://github.com/t-mart/ItemVersion/suites/9794021059/artifacts/471114862

**Comment by t-mart** [comment]
Going to close this for now. I've merged this translation in with #57. Please open another issue if you continue to have problems.
