### ISSUE TITLE
Distorted translation of the phrase

### ISSUE THREAD

**Issue by Hollicsh** [t-mart/ItemVersion#56]
### What is your client flavor? (Retail, Wrath, or Classic)

Retail (10.0.2.46879)

### What version of ItemVersion do you have installed?

2022.48.1

### What platform are you playing on? (Windows, Mac, or Linux)

Windows

### What is the bug? And, what should happen instead?

The mistake is that the translation of the phrase is completely distorted.

Phrase: **L["Copy and paste this data when making a new issue for ItemVersion."]**

### Additional context

![Screenshot_9](https://user-images.githubusercontent.com/54585769/205307601-4b6136a1-1980-40df-a135-8338310f0bbd.png)

**Comment by t-mart** [comment]
I'm sure this will be fixed with your changes in #55. Thanks!

**Comment by t-mart** [comment]
Merged in #55
