### ISSUE TITLE
still koKR Error!!!

### ISSUE THREAD

**Issue by next96** [t-mart/ItemVersion#59]
### What is your client flavor? (Retail, Wrath, or Classic)

all

### What version of ItemVersion do you have installed?

your build

### What platform are you playing on? (Windows, Mac, or Linux)

windows

### What is the bug? And, what should happen instead?

`1x AceLocale-3.0-6: ItemVersion: Missing entry for '용군단'
[string "@ItemVersion/Tooltip.lua"]:57: in function <ItemVersion/Tooltip.lua:42>
[string "=(tail call)"]: ?
[string "@ItemVersion/Options.lua"]:25: in function <ItemVersion/Options.lua:9>
[string "@ItemVersion/Options.lua"]:239: in function <ItemVersion/Options.lua:68>
[string "@ItemVersion/Options.lua"]:258: in function `New'
[string "@ItemVersion/Init.lua"]:13: in function <ItemVersion/Init.lua:7>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>`

The build you gave me also gives the same error.

**Comment by t-mart** [comment]
Ah, I'm sorry about this. Thanks for your patience.

This will be fixed by #61.

I will make another release soon.

**Comment by t-mart** [comment]
Try this release: https://www.curseforge.com/wow/addons/itemversion/files/4166697

**Comment by next96** [comment]
thank you

error fix !!!!!

have a nice day !!
