### ISSUE TITLE
Large Crate of Salvage

### ISSUE THREAD

**Issue by SteveBean317** [t-mart/ItemVersion#88]
### In which flavor are you seeing the wrong version?

- [ ] Vanilla
- [ ] Classic
- [X] Retail

### Are you using the latest version of ItemVersion?

Yes

### Wowhead URL(s) for item.

https://www.wowhead.com/item=140590/large-crate-of-salvage

### How are you encountering this item? Is it in your bags? A chat link? Some other part of the UI?

it's in my bags

### What should this item's expansion/version be instead, and **why**?

it should be WoD since it was from the Garrison Salvage Yard. ATT reports it as WoD, also.

**Comment by t-mart** [comment]
Hey, thanks for reporting.

I understand that the Salvage Yard was a WoD feature, but this item appears to only have come in Legion. It seems like it was a power adjustment to buff/nerf the Salvage Yard in the context of a later expansion.

ItemVersion answers the question, "During which version of the game was an item introduced?". Accurately, the answer here is "Legion".

It seems like you're hoping ItemVersion can also answer "To which version of the game is an item related?", which would likely be WoD.

A feature we have called "Community Updates" can override an item's version. Currently, they are only used by [the Shadowlands herbs that were quietly introduced at the end of BFA, but were not obtainable in-game until SL actually released](https://github.com/t-mart/ItemVersion/blob/master/ItemVersion/Community.lua#L18).

I'm trying to consider if Large Crate of Salvage is a valid use case for Community Updates. One important difference I see here is that, for the herbs, we correct to the version in which they can first be obtained -- but for Crate of Salvage, we'd be correcting to a version (WoD) in which the item could **not** be obtained.

I'm leaning "No" on this. If you have any comments, I'll consider them, but will probably close this issue the next time I think about it.

**Comment by t-mart** [comment]
>  ATT reports it as WoD, also.

Also, what's ATT?

**Comment by SteveBean317** [comment]
Thanks for the quick response. ATT is "All The Things" mod.

I'm fine with whatever you decide. It's just confusing to me to have it listed as Legion since you can't use it outside of WoD; this item is obtained from Garrison Follower missions and only usable in the Garrison Salvage Yard. I guess Blizzard re-used an ID or something when they reduced the BOE drop rate from the crates. 

Thanks for the consideration!

**Comment by t-mart** [comment]
Yeah, I've got to stick to my hunch here and decline this work. If we "opened the door" on changing versions to be whichever they are most related, it'd:

- cloudy the mission of ItemVersion
- not be automatable, and therefore require a ton of manual work
- result in subjective (not objective) decisions

It's easier and more authoritative to just report the version of introduction to the game.
